### PR TITLE
fix: bug fixes and update ruby

### PR DESCRIPTION
**Pull request by razvanazamfirei**
The Heroku app was down so I made some minor changes to make it compatible with recent package versions in case you were planning on maintaining it.

Changes:
Updated to recent ruby and bundler version
Fixed deprecated syntax

### CODE REVIEW

**Comment by joshka** [comment]
Thanks - I've pushed your changes, but I also need to update the heroku stat (from Cedar 14 to 22 lol)

**Comment by joshka** [comment]
Ha, actually I just discovered that heroku stopped offering their free dynos. I might have to find somewhere else to move this. I might be a little delayed in that. Apologies in advance.

**Comment by razvanazamfirei** [comment]
No worries and no rush! I think fly.io still has free plans!

**Comment by joshka** [comment]
Thanks - that worked see https://xkcd-with-alt-text.joshka.net/ for the updated feed

**Pull request merged**
